/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import DTO.LibroDTO;
import Excepcion.NegocioException;
import Negocio.LibroBO;
import guardado.Guardado;
import interfaces.ILibroBO;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author skevi
 */
public class BuscarPorTituloForm extends javax.swing.JFrame {

    private ILibroBO libros;
    private int pagina = 0;
    private int contadorPagina = 1;
    private final int LIMITE = 4;
    private JButton[] botones;
    private JLabel[] labels;
    private int totalPaginas;
    private List<LibroDTO> librosCargados;

    /**
     * Creates new form Menu
     */
    public BuscarPorTituloForm() {
        initComponents();
        this.librosCargados = new ArrayList<>();
        this.libros = new LibroBO();
        this.setSize(380, 600);
        this.setLocationRelativeTo(this);
        this.botones = new JButton[4];
        botones[0] = btnLibro1;
        botones[1] = btnLibro2;
        botones[2] = btnLibro3;
        botones[3] = btnLibro4;
        this.labels = new JLabel[4];
        labels[0] = txtLibro1;
        labels[1] = txtLibro2;
        labels[2] = txtLibro3;
        labels[3] = txtLibro4;
        this.cargarMetodosIniciales();

    }

    private void cargarMetodosIniciales() {
        this.cargarLibros();
        btnAtras.setEnabled(false);
        TituloField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                // Llamar al método cargarLibros() cada vez que se inserte texto en el campo de texto
                cargarLibros();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                // Llamar al método cargarLibros() cada vez que se elimine texto del campo de texto
                cargarLibros();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                // Este método se llama cuando ocurre un cambio en los atributos del documento, 
                // como un cambio en el estilo del texto, pero no necesitamos hacer nada en este caso
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtLibro1 = new javax.swing.JLabel();
        txtLibro2 = new javax.swing.JLabel();
        txtLibro3 = new javax.swing.JLabel();
        txtLibro4 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        contPagina = new javax.swing.JLabel();
        btnLibro1 = new javax.swing.JButton();
        btnLibro2 = new javax.swing.JButton();
        btnLibro3 = new javax.swing.JButton();
        btnLibro4 = new javax.swing.JButton();
        TituloField = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        brnUsuario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        txtLibro1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtLibro1.setText("EL PODER DE ESTAR SOLO");
        txtLibro1.setToolTipText("");

        txtLibro2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtLibro2.setText("EL PAIS DE UN SOLO HOMBRE");

        txtLibro3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtLibro3.setText("PERCY JACKSON");

        txtLibro4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtLibro4.setText("ORGULLO Y PREJUICIO");

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angulo-izquierdo.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angulo-derecho.png"))); // NOI18N
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        contPagina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contPagina.setText("1");

        btnLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro1ActionPerformed(evt);
            }
        });

        btnLibro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro2ActionPerformed(evt);
            }
        });

        btnLibro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro3ActionPerformed(evt);
            }
        });

        btnLibro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro4ActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/busqueda.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtLibro3)
                                .addGap(56, 56, 56))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAtras)
                                .addGap(18, 18, 18)
                                .addComponent(contPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLibro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLibro3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLibro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSiguiente)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLibro2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLibro4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLibro2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLibro4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(TituloField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TituloField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLibro2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(btnLibro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLibro1)
                    .addComponent(txtLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLibro4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLibro4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtras)
                    .addComponent(contPagina)
                    .addComponent(btnSiguiente))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        brnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha-pequena-izquierda.png"))); // NOI18N
        brnUsuario.setContentAreaFilled(false);
        brnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnUsuarioActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu-hamburguesa.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Menu Principal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brnUsuario)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addGap(62, 62, 62)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brnUsuario)
                            .addComponent(jButton1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarLibros() {
        String titulo = TituloField.getText();

        try {
            this.totalPaginas = (int) Math.ceil((double) this.libros.listaLibrosTitulo(titulo).size() / this.LIMITE);
            // Calcular el índice inicial del libro para esta página
            int startIndex = this.pagina * this.LIMITE;

            if (!libros.listaLibrosTitulo(titulo).isEmpty()) {
                int endIndex = Math.min(startIndex + this.LIMITE, this.libros.listaLibrosTitulo(titulo).size());

                // Obtener la sublista de libros para esta página
                List<LibroDTO> libroLista = this.libros.listaLibrosTitulo(titulo).subList(startIndex, endIndex);

                librosCargados.clear();
                librosCargados.addAll(libroLista);
                System.out.println(libroLista.size());

                this.llenarCampos(libroLista);
            } else {
                librosCargados.clear();
                for (int i = 0; i < LIMITE; i++) {
                    ImageIcon icono = new ImageIcon(getClass().getResource("/images/soon.jpg"));
                    Image scaledImage = icono.getImage().getScaledInstance(100, 150, Image.SCALE_SMOOTH);
                    botones[i].setIcon(new ImageIcon(scaledImage));
                    labels[i].setText(""); // Limpiar texto
                    botones[i].setEnabled(false); // Desactivar botón
                }
                this.verificarBotonesNavegacion();
                JOptionPane.showMessageDialog(rootPane, ("No se encontro ningun Libro"), "Busqueda", HEIGHT);

            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Información", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void llenarCampos(List<LibroDTO> libroLista) throws NegocioException {
        if (libroLista.isEmpty()) {
            throw new NegocioException("Ningun Libro");
        }
        for (int i = 0; i < libroLista.size(); i++) {
            botones[i].setVisible(true);
            labels[i].setVisible(true);
            botones[i].setEnabled(true);
            ImageIcon icon = new ImageIcon(libroLista.get(i).getPortadaDTO());
            Image scaledImage = icon.getImage().getScaledInstance(100, 150, Image.SCALE_SMOOTH);
            botones[i].setIcon(new ImageIcon(scaledImage));
            labels[i].setText(libroLista.get(i).getTituloDTO());
        }
        // Limpiar botones y etiquetas restantes
        for (int i = libroLista.size(); i < LIMITE; i++) {
            ImageIcon icono = new ImageIcon(getClass().getResource("/images/soon.jpg"));
            Image scaledIcono = icono.getImage().getScaledInstance(100, 150, Image.SCALE_SMOOTH);
            botones[i].setIcon(new ImageIcon(scaledIcono));
            labels[i].setText("");
            botones[i].setEnabled(false);

        }

        this.verificarBotonesNavegacion();

    }


    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        contadorPagina++;
        contPagina.setText(String.valueOf(contadorPagina));
        if (this.botones[3].isEnabled()) {
            this.pagina++;
            this.cargarLibros();
            this.verificarBotonesNavegacion();
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed
    private void verificarBotonesNavegacion() {
        btnAtras.setEnabled(this.pagina > 0);
        btnSiguiente.setEnabled(this.botones[3].isEnabled());
        TituloField.setEnabled(contadorPagina <= 1);

    }
    private void btnLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro1ActionPerformed
        LibroDTO libro = librosCargados.get(0);
        Guardado.setIsbn(libro.getISBNDTO());
        Libro_presentacion libroForm = new Libro_presentacion();
        libroForm.setVisible(true);
    }//GEN-LAST:event_btnLibro1ActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        contadorPagina--;
        contPagina.setText(String.valueOf(contadorPagina));
        if (this.pagina > 0) {
            this.pagina--;
            this.cargarLibros();
            this.verificarBotonesNavegacion();
        }

    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLibro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro2ActionPerformed

        LibroDTO libro = librosCargados.get(1);
        Guardado.setIsbn(libro.getISBNDTO());

        Libro_presentacion libroForm = new Libro_presentacion();
        libroForm.setVisible(true);

    }//GEN-LAST:event_btnLibro2ActionPerformed

    private void btnLibro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro3ActionPerformed
        LibroDTO libro = librosCargados.get(2);
        Guardado.setIsbn(libro.getISBNDTO());

        Libro_presentacion libroForm = new Libro_presentacion();
        libroForm.setVisible(true);

    }//GEN-LAST:event_btnLibro3ActionPerformed

    private void btnLibro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro4ActionPerformed
        LibroDTO libro = librosCargados.get(3);
        Guardado.setIsbn(libro.getISBNDTO());

        Libro_presentacion libroForm = new Libro_presentacion();
        libroForm.setVisible(true);

    }//GEN-LAST:event_btnLibro4ActionPerformed
    private void brnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brnUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPorTituloForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPorTituloForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPorTituloForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPorTituloForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarPorTituloForm().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TituloField;
    private javax.swing.JButton brnUsuario;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLibro1;
    private javax.swing.JButton btnLibro2;
    private javax.swing.JButton btnLibro3;
    private javax.swing.JButton btnLibro4;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel contPagina;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtLibro1;
    private javax.swing.JLabel txtLibro2;
    private javax.swing.JLabel txtLibro3;
    private javax.swing.JLabel txtLibro4;
    // End of variables declaration//GEN-END:variables
}
