/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import guardado.Guardado;
import javax.swing.JButton;

/**
 *
 * @author Rios
 */
public class BuscarForm extends javax.swing.JFrame {

    JButton botones[];
    private boolean botonesGeneroVisible;

    /**
     * Creates new form Menu
     */
    public BuscarForm() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setSize(1119, 639);
        this.setResizable(false);
        botonesGeneroVisible = false;
        botones = new JButton[]{AccionButton, AventuraButton, ComediaButton, DramaButton, FantasiaButton, FiccionButton,
            HistoriaButton, InfantilButton, NovelaButton, PoesiaButton, RealidadButton, RomanceButton,
            SuspensoButton, TerrorButton};
        this.desactivarBotones();
    }

    public void desactivarBotones() {
        for (JButton boton : botones) {
            boton.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IsbnButton = new javax.swing.JButton();
        TituloButton = new javax.swing.JButton();
        GeneroButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        brnUsuario = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        FiccionButton = new javax.swing.JButton();
        DramaButton = new javax.swing.JButton();
        TerrorButton = new javax.swing.JButton();
        HistoriaButton = new javax.swing.JButton();
        NovelaButton = new javax.swing.JButton();
        RomanceButton = new javax.swing.JButton();
        RealidadButton = new javax.swing.JButton();
        SuspensoButton = new javax.swing.JButton();
        AccionButton = new javax.swing.JButton();
        PoesiaButton = new javax.swing.JButton();
        AventuraButton = new javax.swing.JButton();
        InfantilButton = new javax.swing.JButton();
        ComediaButton = new javax.swing.JButton();
        FantasiaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");
        setBackground(new java.awt.Color(88, 88, 95));

        jPanel1.setBackground(new java.awt.Color(88, 88, 95));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IsbnButton.setBackground(new java.awt.Color(88, 138, 135));
        IsbnButton.setText("ISBN");
        IsbnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsbnButtonActionPerformed(evt);
            }
        });
        jPanel1.add(IsbnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 206, 190, 50));

        TituloButton.setBackground(new java.awt.Color(88, 138, 135));
        TituloButton.setText("Titulo");
        TituloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloButtonActionPerformed(evt);
            }
        });
        jPanel1.add(TituloButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 144, 190, 50));

        GeneroButton.setBackground(new java.awt.Color(88, 138, 135));
        GeneroButton.setText("Genero");
        GeneroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroButtonActionPerformed(evt);
            }
        });
        jPanel1.add(GeneroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 268, 190, 50));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 48)); // NOI18N
        jLabel2.setText("Buscar por:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jPanel2.setBackground(new java.awt.Color(88, 138, 135));

        brnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha-pequena-izquierda.png"))); // NOI18N
        brnUsuario.setContentAreaFilled(false);
        brnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1060, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(brnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1138, 70));

        jPanel3.setBackground(new java.awt.Color(88, 88, 95));

        FiccionButton.setText("Ficcion");
        FiccionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiccionButtonActionPerformed(evt);
            }
        });

        DramaButton.setText("Drama");
        DramaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DramaButtonActionPerformed(evt);
            }
        });

        TerrorButton.setText("Terror");
        TerrorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerrorButtonActionPerformed(evt);
            }
        });

        HistoriaButton.setText("Historia");
        HistoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoriaButtonActionPerformed(evt);
            }
        });

        NovelaButton.setText("Novela");
        NovelaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovelaButtonActionPerformed(evt);
            }
        });

        RomanceButton.setText("Romance");
        RomanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RomanceButtonActionPerformed(evt);
            }
        });

        RealidadButton.setText("Realidad");
        RealidadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealidadButtonActionPerformed(evt);
            }
        });

        SuspensoButton.setText("Suspenso");
        SuspensoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuspensoButtonActionPerformed(evt);
            }
        });

        AccionButton.setText("Accion");
        AccionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionButtonActionPerformed(evt);
            }
        });

        PoesiaButton.setText("Poesia");
        PoesiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoesiaButtonActionPerformed(evt);
            }
        });

        AventuraButton.setText("Aventura");
        AventuraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AventuraButtonActionPerformed(evt);
            }
        });

        InfantilButton.setText("Infantil");
        InfantilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfantilButtonActionPerformed(evt);
            }
        });

        ComediaButton.setText("Comedia");
        ComediaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComediaButtonActionPerformed(evt);
            }
        });

        FantasiaButton.setText("Fantasia");
        FantasiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FantasiaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SuspensoButton)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DramaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PoesiaButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HistoriaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RealidadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InfantilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AventuraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NovelaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ComediaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(TerrorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FiccionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FantasiaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(RomanceButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(RealidadButton)
                        .addGap(15, 15, 15)
                        .addComponent(DramaButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InfantilButton)
                            .addComponent(TerrorButton))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NovelaButton)
                            .addComponent(ComediaButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AventuraButton)
                            .addComponent(PoesiaButton)
                            .addComponent(FantasiaButton))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HistoriaButton)
                        .addComponent(AccionButton))
                    .addComponent(FiccionButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuspensoButton)
                    .addComponent(RomanceButton))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 420, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IsbnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsbnButtonActionPerformed
        BuscarPorISBNForm buscarISBN = new BuscarPorISBNForm();
        buscarISBN.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IsbnButtonActionPerformed

    private void TituloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloButtonActionPerformed
        BuscarPorTituloForm buscarTitulo = new BuscarPorTituloForm();
        buscarTitulo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TituloButtonActionPerformed

    private void GeneroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroButtonActionPerformed
        this.toggleBotonesGenero();
    }//GEN-LAST:event_GeneroButtonActionPerformed

    private void brnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnUsuarioActionPerformed
        MenuForm menu = new MenuForm();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_brnUsuarioActionPerformed

    private void FiccionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiccionButtonActionPerformed
        String genero = FiccionButton.getText();
        Guardado.setGenero(genero);
        BuscarPorGeneroForm buscarGenero = new BuscarPorGeneroForm();
        buscarGenero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FiccionButtonActionPerformed

    private void DramaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DramaButtonActionPerformed
        String genero = DramaButton.getText();
        Guardado.setGenero(genero);
        BuscarPorGeneroForm buscarGenero = new BuscarPorGeneroForm();
        buscarGenero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DramaButtonActionPerformed

    private void TerrorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerrorButtonActionPerformed
        String genero = TerrorButton.getText();
        Guardado.setGenero(genero);
        BuscarPorGeneroForm buscarGenero = new BuscarPorGeneroForm();
        buscarGenero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TerrorButtonActionPerformed

    private void HistoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoriaButtonActionPerformed
        String genero = HistoriaButton.getText();
        Guardado.setGenero(genero);
        BuscarPorGeneroForm buscarGenero = new BuscarPorGeneroForm();
        buscarGenero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HistoriaButtonActionPerformed

    private void NovelaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovelaButtonActionPerformed
        String genero = NovelaButton.getText();
        Guardado.setGenero(genero);
        BuscarPorGeneroForm buscarGenero = new BuscarPorGeneroForm();
        buscarGenero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NovelaButtonActionPerformed

    private void RomanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RomanceButtonActionPerformed
        String genero = RomanceButton.getText();
        Guardado.setGenero(genero);
        BuscarPorGeneroForm buscarGenero = new BuscarPorGeneroForm();
        buscarGenero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RomanceButtonActionPerformed

    private void RealidadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealidadButtonActionPerformed
        String genero = RealidadButton.getText();
        Guardado.setGenero(genero);
        BuscarPorGeneroForm buscarGenero = new BuscarPorGeneroForm();
        buscarGenero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RealidadButtonActionPerformed

    private void SuspensoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuspensoButtonActionPerformed
        String genero = SuspensoButton.getText();
        Guardado.setGenero(genero);
        BuscarPorGeneroForm buscarGenero = new BuscarPorGeneroForm();
    }//GEN-LAST:event_SuspensoButtonActionPerformed

    private void AccionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionButtonActionPerformed
        String genero = AccionButton.getText();
        Guardado.setGenero(genero);
        BuscarPorGeneroForm buscarGenero = new BuscarPorGeneroForm();
        buscarGenero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AccionButtonActionPerformed

    private void PoesiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoesiaButtonActionPerformed
        String genero = PoesiaButton.getText();
        Guardado.setGenero(genero);
        BuscarPorGeneroForm buscarGenero = new BuscarPorGeneroForm();
        buscarGenero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PoesiaButtonActionPerformed

    private void AventuraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AventuraButtonActionPerformed
        String genero = AventuraButton.getText();
        Guardado.setGenero(genero);
        BuscarPorGeneroForm buscarGenero = new BuscarPorGeneroForm();
        buscarGenero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AventuraButtonActionPerformed

    private void InfantilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfantilButtonActionPerformed
        String genero = InfantilButton.getText();
        Guardado.setGenero(genero);
        BuscarPorGeneroForm buscarGenero = new BuscarPorGeneroForm();
        buscarGenero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InfantilButtonActionPerformed

    private void ComediaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComediaButtonActionPerformed
        String genero = ComediaButton.getText();
        Guardado.setGenero(genero);
        BuscarPorGeneroForm buscarGenero = new BuscarPorGeneroForm();
        buscarGenero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ComediaButtonActionPerformed

    private void FantasiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FantasiaButtonActionPerformed
        String genero = FantasiaButton.getText();
        Guardado.setGenero(genero);
        BuscarPorGeneroForm buscarGenero = new BuscarPorGeneroForm();
        buscarGenero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FantasiaButtonActionPerformed

    private void toggleBotonesGenero() {
        botonesGeneroVisible = !botonesGeneroVisible;
        for (JButton boton : botones) {
            boton.setVisible(botonesGeneroVisible);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarForm().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccionButton;
    private javax.swing.JButton AventuraButton;
    private javax.swing.JButton ComediaButton;
    private javax.swing.JButton DramaButton;
    private javax.swing.JButton FantasiaButton;
    private javax.swing.JButton FiccionButton;
    private javax.swing.JButton GeneroButton;
    private javax.swing.JButton HistoriaButton;
    private javax.swing.JButton InfantilButton;
    private javax.swing.JButton IsbnButton;
    private javax.swing.JButton NovelaButton;
    private javax.swing.JButton PoesiaButton;
    private javax.swing.JButton RealidadButton;
    private javax.swing.JButton RomanceButton;
    private javax.swing.JButton SuspensoButton;
    private javax.swing.JButton TerrorButton;
    private javax.swing.JButton TituloButton;
    private javax.swing.JButton brnUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
