/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;


/**
 *
 * @author Usuario
 */
public class MenuAdministradorForm extends javax.swing.JFrame {

    /**
     * Creates new form InicioCasoUso
     */
    public MenuAdministradorForm() {
        initComponents();
        setResizable(false); // Hace que el JFrame no sea redimensionable

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ConsultarAlumnosButton = new javax.swing.JButton();
        ConsultarPrestamosButton = new javax.swing.JButton();
        AgregarLibroButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ConsultarVentasButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin");

        jPanel1.setBackground(new java.awt.Color(88, 88, 95));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ConsultarAlumnosButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 12)); // NOI18N
        ConsultarAlumnosButton.setText("Consultar Alumnos");
        ConsultarAlumnosButton.setToolTipText("");
        ConsultarAlumnosButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ConsultarAlumnosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarAlumnosButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ConsultarAlumnosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 140, 30));

        ConsultarPrestamosButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 12)); // NOI18N
        ConsultarPrestamosButton.setText("Consultar Prestamos");
        ConsultarPrestamosButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ConsultarPrestamosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarPrestamosButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ConsultarPrestamosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 140, 30));

        AgregarLibroButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        AgregarLibroButton.setText("Agregar Libro");
        AgregarLibroButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AgregarLibroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarLibroButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarLibroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, 30));

        jPanel2.setBackground(new java.awt.Color(88, 138, 135));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 36)); // NOI18N
        jLabel1.setText("Menu Administrador");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 70));

        ConsultarVentasButton1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 12)); // NOI18N
        ConsultarVentasButton1.setText("Consultar Ventas");
        ConsultarVentasButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ConsultarVentasButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarVentasButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(ConsultarVentasButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarPrestamosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarPrestamosButtonActionPerformed
        ConsultarLibrosPrestamoForm consultar = new ConsultarLibrosPrestamoForm();
        consultar.setVisible(true);
        dispose();    }//GEN-LAST:event_ConsultarPrestamosButtonActionPerformed

    private void AgregarLibroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarLibroButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarLibroButtonActionPerformed

    private void ConsultarAlumnosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarAlumnosButtonActionPerformed
        ConsultarAlumnosForm consultar = new ConsultarAlumnosForm();
        consultar.setVisible(true);
        dispose();

    }//GEN-LAST:event_ConsultarAlumnosButtonActionPerformed

    private void ConsultarVentasButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarVentasButton1ActionPerformed
        ConsultarLibrosVentaForm consultar = new ConsultarLibrosVentaForm();
        consultar.setVisible(true);

        dispose();    }//GEN-LAST:event_ConsultarVentasButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministradorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarLibroButton;
    private javax.swing.JButton ConsultarAlumnosButton;
    private javax.swing.JButton ConsultarPrestamosButton;
    private javax.swing.JButton ConsultarVentasButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
